### ISSUE TITLE
Creating a new tour with a title that already exists modifies the existing tour

### ISSUE THREAD

**Issue by trymebytes** [Automattic/tour#1]
### Problem
Whenever the form to create a new tour is loaded, the title field is pre-filled with the text `Test`.  Users can easily modify an already existing tour with the title "Test" if they do not change this title to something unique. 
<img width="1008" alt="Screenshot 2023-10-24 at 21 14 36" src="https://github.com/Automattic/tour/assets/2834132/a03faae6-7164-4364-9cfb-3734e58e5859">

### Solution
Set the title field to empty and prevent the user from proceeding to the next step until a unique tour title is specified. We may also append a number automatically to avoid reusing an existing tour title. For example, where a tour named `Test` already exists and a user tries to save a new tour with the title `Test`, the new tour title is automatically saved as `Test-1`

**Comment by akirk** [comment]
Indeed, if you add a tour on the same page you need to reload without pressing Update. The steps are saved to the tour on the server side through JS but not to the form that you are seeing, so it contains the tour at the state before you added the steps. You'll thus find them in the revision history. I wonder how to fix that, should we reload the page if we are on still on the tour edit screen?

**Comment by akirk** [comment]
Since we switched to using post ids, this should be fixed.
